// @flow

export const UPDATE_CONFIG ='UPDATE_CONFIG';

export const FETCH_PROBLEMS_REQUEST = 'FETCH_PROBLEMS_REQUEST';
export const CLOSE_WORK_IN_PROGRESS_WINDOW = 'CLOSE_WORK_IN_PROGRESS_WINDOW';

export const FETCH_RAW_PROBLEMS = 'FETCH_RAW_PROBLEMS';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
